steps:
  # שלב בדיקה: מדפיס את כל התיקיות והקבצים שהשרת של גוגל באמת רואה
  - name: 'ubuntu'
    args: ['ls', '-R']

  # שלב 1 המתוקן: הוספת הגדרת המיקום המדויק בשרת
  - name: 'python'
    entrypoint: pip
    dir: '.'
    args: ["install", "-r", "utils/requirements.txt", "--user"]


steps:
  # Step 1: Install Python dependencies
  - name: 'python'
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user"]

  # Step 2: Run the script to upload DAGs and Data to Composer bucket
  - name: 'python'
    entrypoint: python
    args:
      - "utils/add_dags_to_composer.py"
      - "--dags_directory=${_DAGS_DIRECTORY}"
      - "--dags_bucket=${_DAGS_BUCKET}"
      - "--data_directory=${_DATA_DIRECTORY}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DAGS_DIRECTORY: "workflows/"
  _DAGS_BUCKET: "us-central1-demo-instens-f74604bd-bucket" # Replace with your Composer bucket
  _DATA_DIRECTORY: "data/"
